# Site settings
author: Mark Ehler
title: Deeper Thinking
header-img: img/home-bg.png
email: ehlerm42@gmail.com
copyright_name: Mark Ehler
description: > # this means to ignore newlines until "baseurl:"
  Tiny details and how they fit into the bigger picture 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  MarkEhler

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
